/**
 * Assembler - 模块组装器
 * 对应手册：assemble 组装
 */
import { compute } from './fca.js';
import { computeExecutionOrder } from './koncept.js';

export function generateChannels(state) {
  // 从 schemas 生成 Channel 类型定义
  const lines = ['// Channel type definitions'];
  for (const [aid, schema] of Object.entries(state.schemas)) {
    const attr = state.attributes[aid];
    if (attr) {
      lines.push(`// Channel: ${attr.name}`);
      lines.push(`const ${attr.name}Schema = ${schema};`);
    }
  }
  return lines.join('\n');
}

export function generateContracts(state) {
  // 从 I 矩阵生成 Contracts
  const reads = {};    // module -> [channels]
  const writes = {};   // module -> [channels]
  const readwrites = {}; // module -> [channels]

  for (const [oid, obj] of Object.entries(state.objects)) {
    reads[oid] = [];
    writes[oid] = [];
    readwrites[oid] = [];

    for (const [aid, attr] of Object.entries(state.attributes)) {
      const v = state.incidence[`${oid}|${aid}`] || '0';
      const channelName = attr.name;
      if (v === 'R') reads[oid].push(channelName);
      else if (v === 'W') writes[oid].push(channelName);
      else if (v === 'RW') readwrites[oid].push(channelName);
    }
  }

  const lines = ['// Contracts'];
  for (const [oid, obj] of Object.entries(state.objects)) {
    lines.push(`// ${obj.name} (${oid})`);
    if (reads[oid].length) lines.push(`//   reads: ${reads[oid].join(', ')}`);
    if (writes[oid].length) lines.push(`//   writes: ${writes[oid].join(', ')}`);
    if (readwrites[oid].length) lines.push(`//   readwrites: ${readwrites[oid].join(', ')}`);
  }
  return lines.join('\n');
}

export function assemble(state, outputFile, fs) {
  const result = compute(state.objects, state.attributes, state.incidence);
  const order = computeExecutionOrder(state);

  const parts = [];

  // 1. 头部
  parts.push(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Assembled from KonceptOS</title>
</head>
<body>
<script>
// === GENERATED BY KONCEPTOS ===
// DO NOT EDIT - Regenerate with: konceptos assemble

`);

  // 2. Channels 类型定义
  if (Object.keys(state.schemas).length) {
    parts.push('// --- Channels ---\n');
    parts.push(generateChannels(state));
    parts.push('\n');
  }

  // 3. Contracts
  parts.push('// --- Contracts ---\n');
  parts.push(generateContracts(state));
  parts.push('\n');

  // 4. Conventions
  if (state.conventions) {
    parts.push('// --- Conventions ---\n');
    parts.push(`// ${state.conventions.split('\n').join('\n// ')}`);
    parts.push('\n');
  }

  // 5. ChannelStore
  parts.push(`// --- ChannelStore ---
const state = {};

function read(channel) {
  if (!state[channel]) state[channel] = {};
  return state[channel];
}

function write(channel, data) {
  state[channel] = { ...state[channel], ...data };
}
`);

  // 6. 模块实现
  const modules = order.map(oid => state.objects[oid]).filter(Boolean);
  const missingImpls = [];

  for (const obj of modules) {
    parts.push(`\n// --- Module: ${obj.name} ---\n`);
    const impls = state.impls[obj.name];
    if (impls && impls.length > 0) {
      const latest = impls[impls.length - 1];
      parts.push(latest.code);
    } else {
      missingImpls.push(obj.name);
      parts.push(`// TODO: ${obj.name} - no impl available`);
    }
  }

  // 7. Game Loop
  parts.push(`
// --- Game Loop ---
function gameLoop() {
  update();
  render();
  requestAnimationFrame(gameLoop);
}

function update() {
  ${order.join('(); ')}();
}

function render() {
  // Render logic
}

gameLoop();
</script>
</body>
</html>`);

  if (missingImpls.length > 0) {
    console.warn(`\n⚠️  Missing impls: ${missingImpls.join(', ')}`);
  }

  if (fs) {
    fs.writeFileSync(outputFile, parts.join('\n'));
  }

  return { code: parts.join('\n'), missingImpls };
}
