/**
 * CSS Generator - 生成样式文件
 */
export function generateCSS() {
  const lines = [
    '/**',
    ' * Style - 样式表',
    ' * 自动生成',
    ' */',
    '',
    '* {',
    '  margin: 0;',
    '  padding: 0;',
    '  box-sizing: border-box;',
    '}',
    '',
    'body {',
    '  font-family: system-ui, -apple-system, sans-serif;',
    '  background: #1a1a2e;',
    '  color: #eee;',
    '  min-height: 100vh;',
    '  display: flex;',
    '  justify-content: center;',
    '  align-items: center;',
    '}',
    '',
    '#game-container {',
    '  position: relative;',
    '}',
    '',
    '#game {',
    '  border: 2px solid #4a4a6a;',
    '  border-radius: 4px;',
    '  background: #000;',
    '}',
    '',
    '#debug-panel {',
    '  position: fixed;',
    '  top: 10px;',
    '  right: 10px;',
    '  background: rgba(0, 0, 0, 0.8);',
    '  padding: 10px;',
    '  border-radius: 4px;',
    '  font-family: monospace;',
    '  font-size: 12px;',
    '}',
    '',
    '#debug-panel h3 {',
    '  margin-bottom: 8px;',
    '  color: #4a9eff;',
    '}',
    '',
    '#debug-panel > div {',
    '  margin: 4px 0;',
    '}',
    ''
  ];

  return lines.join('\n');
}
