/**
 * Main Loop Generator - 生成主循环
 */
export function generateMain(order, objects) {
  const modules = Object.values(objects).map(o => o.name);

  const lines = [
    '/**',
    ' * Main - 游戏主循环',
    ' * 自动生成',
    ' */',
    '',
    'import { initAll, updateAll, renderAll } from "./modules/index.js";',
    '',
    'let lastTime = 0;',
    'let canvas, ctx;',
    '',
    '/**',
    ' * 初始化',
    ' */',
    'function init() {',
    '  console.log("Initializing...");',
    '  ',
    '  canvas = document.getElementById("game");',
    '  ctx = canvas?.getContext("2d");',
    '  ',
    '  initAll();',
    '  console.log("Initialized.");',
    '}',
    '',
    '/**',
    ' * 主循环',
    ' */',
    'function gameLoop(timestamp) {',
    '  const dt = (timestamp - lastTime) / 1000; // delta time in seconds',
    '  lastTime = timestamp;',
    '  ',
    '  // Update',
    '  updateAll(dt);',
    '  ',
    '  // Render',
    '  if (ctx) {',
    '    ctx.clearRect(0, 0, canvas.width, canvas.height);',
    '    renderAll(ctx);',
    '  }',
    '  ',
    '  requestAnimationFrame(gameLoop);',
    '}',
    '',
    '/**',
    ' * 启动',
    ' */',
    'export function start() {',
    '  console.log("Starting game...");',
    '  init();',
    '  requestAnimationFrame(gameLoop);',
    '}',
    '',
    '/**',
    ' * 停止',
    ' */',
    'export function stop() {',
    '  console.log("Game stopped.");',
    '}',
    '',
    '// 自动启动',
    'if (typeof document !== "undefined") {',
    '  document.addEventListener("DOMContentLoaded", start);',
    '}',
    ''
  ];

  return lines.join('\n');
}
